version: "2"
services:
    proxy:
        build: ./
        ports:
            - "80:80"
        networks:
            - app-network
        extra_hosts:
            - "host.docker.internal:host-gateway"

networks:
    app-network:
        driver: bridge
